name = "Microbiome"
uuid = "3bd8f0ae-a0f2-5238-a5af-e1b399a4940c"
keywords = ["microbiology", "microbiome", "biology"]
license = "MIT"
desc = "Functions for working with microbial community data"
authors = ["kescobo <kevbonham@gmail.com>"]
version = "0.5.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SpatialEcology = "348f2d5d-71a3-5ad4-b565-8af070f99681"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
julia = "1.1, 1.2"

[extras]
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
coverage = ["Coverage"]
test = ["Test", "Random"]
