name = "Microbiome"
uuid = "3bd8f0ae-a0f2-5238-a5af-e1b399a4940c"
keywords = ["microbiology", "microbiome", "biology"]
license = "MIT"
desc = "Functions and types for working with microbial community data"
authors = ["@kescobo <kevbonham@gmail.com>"]
version = "0.7.1"

[deps]
AxisIndices = "f52c9ee2-1b1c-4fd8-8546-6350938c7f11"
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
EcoBase = "a58aae7d-b440-5a11-b283-399458f99aac"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
NamedDims = "356022a1-0364-5f58-8944-0da4b18d706f"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
AxisIndices = "0.7"
Dictionaries = "0.3"
Distances = "0.10"
EcoBase = "0.1"
MultivariateStats = "0.7, 0.8"
NamedDims = "0.2"
Tables = "1.2.1"
julia = "1.1"

[extras]
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
coverage = ["Coverage"]
test = ["Test", "Random"]
