[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Microbiome = "3bd8f0ae-a0f2-5238-a5af-e1b399a4940c"
MicrobiomePlots = "bed85cf4-5cc8-5ac4-9eb3-09fbf92b2ce2"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"

[compat]
Documenter = "~0.22"
